'\" t
.\"     Title: dnstable_convert
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 06/17/2021
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "DNSTABLE_CONVERT" "1" "06/17/2021" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dnstable_convert \- convert passive DNS NMSG data to dnstable MTBL format
.SH "SYNOPSIS"
.sp
\fBdnstable_convert\fR [\fB\-D\fR] \fINMSG\-FILE\fR \fIDB\-DNS\-FILE\fR \fIDB\-DNSSEC\-FILE\fR
.SH "DESCRIPTION"
.sp
Converts passive DNS data from NMSG format to MTBL format\&. The input NMSG data in \fINMSG\-FILE\fR must be encoded using the SIE/dnsdedupe message schema, and the output data will be written to two separate MTBL files: the \fIDB\-DNS\-FILE\fR containing "plain" DNS records, and the \fIDB\-DNSSEC\-FILE\fR, containing DNSSEC\-related records\&.
.sp
Specifically, all resource records of type DS, RRSIG, NSEC, DNSKEY, NSEC3, NSEC3PARAM, DLV, CDS, CDNSKEY, and TLV are stored in the \fIDB\-DNSSEC\-FILE\fR, and resource records of all other types are stored in the \fIDB\-DNS\-FILE\fR\&. If the \fB\-D\fR flag is provided then CDS, CDNSKEY, and TLV will also be stored in the \fIDB\-DNS\-FILE\fR file for transition compability\&.
.sp
\fBdnstable_convert\fR will create both the \fIDB\-DNS\-FILE\fR and \fIDB\-DNSSEC\-FILE\fR, and will abort if either exists\&. If the input file contains no DNSSEC\-related records, \fIDB\-DNSSEC\-FILE\fR will be removed\&.
.sp
The output files produced by \fBdnstable_convert\fR are suitable for use with other dnstable tools like \fBdnstable_dump\fR(1) and \fBdnstable_merge\fR(1), or with the \fBdnstable_reader\fR(3) API\&. Since they are in MTBL format, they can also be read with the \fBmtbl_reader\fR(3) API\&.
.sp
By default, \fBdnstable_convert\fR will use \fB/var/tmp/\fR to store temporary mtbl files\&. The optional \fIVARTMPDIR\fR environment variable can be set to override the location\&. Specifying a filesystem for RAM\-based storage or specifying the same filesystem as the source data file might be useful\&.
.SH "OPTIONS"
.PP
\fB\-D\fR
.RS 4
This flag enables a transitional compatibility mode described above\&.
.RE
